import theme from '@/theme';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
});

export const metadata: Metadata = {
  // TODO: Dynamically generate metadata title and description
  title: 'Me.teo weather dashboard',
  description: 'Weather dashboard generated by the "me.teo" WeeWX skin.',
  applicationName: 'Me.teo',
  appleWebApp: {
    capable: true,
    title: 'Me.teo'
  },
  authors: [{ name: 'Pascal Bourque' }],
  category: 'Weather',
  generator: 'WeeWX'
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <meta name="theme-color" content="#3874cb" media="(prefers-color-scheme: light)" />
      <meta name="theme-color" content="#272727" media="(prefers-color-scheme: dark)" />

      <body className={roboto.variable}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <NextIntlClientProvider messages={messages}>{children}</NextIntlClientProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
